import { StyleSheet, Platform } from 'react-native';
import { Colors } from '@/constants/theme';
import { type Scalers } from '@/utils/responsive';

/**
 * Auth screens — Google Material–inspired sign-in UI.
 */
export const authStyles = ({ sw, sh, ms }: Scalers) => StyleSheet.create({
  welcomeContainer: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  welcomeGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: sh(160),
    backgroundColor: 'rgba(0, 42, 64, 0.5)',
  },
  welcomeContentCard: {
    paddingHorizontal: sw(28),
    paddingTop: sh(28),
    paddingBottom: sh(32),
    backgroundColor: Colors.background,
    borderTopLeftRadius: sw(28),
    borderTopRightRadius: sw(28),
    shadowColor: Colors.primaryDark,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: sw(16),
    elevation: 8,
  },
  welcomeDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: sw(10),
    marginBottom: sh(24),
  },
  welcomeDot: {
    height: sh(8),
    borderRadius: sw(4),
    backgroundColor: Colors.border,
  },
  welcomeDotActive: {
    width: sw(24),
    backgroundColor: Colors.primary,
  },
  welcomeTitle: {
    fontSize: ms(26),
    fontWeight: '800',
    color: Colors.textPrimary,
    textAlign: 'center',
    marginBottom: sh(8),
    letterSpacing: -0.5,
  },
  welcomeSubtitle: {
    fontSize: ms(15),
    color: Colors.textSecondary,
    textAlign: 'center',
    marginBottom: sh(28),
    lineHeight: ms(22),
  },
  welcomeButton: {
    backgroundColor: Colors.primary,
    paddingVertical: sh(18),
    borderRadius: sw(16),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: sw(8),
    elevation: 4,
  },
  welcomeButtonText: {
    fontSize: ms(17),
    fontWeight: '700',
    color: Colors.textOnPrimary,
    letterSpacing: 0.3,
  },

  /* ── Sign-in: bottom sheet (screenshot layout) + Finovert brand ───────── */
  loginScrollContent: {
    flexGrow: 1,
    paddingBottom: sh(8),
  },
  loginPage: {
    flex: 1,
    backgroundColor: Colors.gradientDark,
    justifyContent: 'flex-end',
  },
  loginSheet: {
    backgroundColor: Colors.background,
    borderTopLeftRadius: sw(28),
    borderTopRightRadius: sw(28),
    paddingHorizontal: sw(28),
    paddingTop: sh(32),
    paddingBottom: sh(20),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: sw(12),
    elevation: 12,
  },
  loginSheetAboveKeyboard: {
    position: 'absolute',
    left: 0,
    right: 0,
    paddingTop: sh(20),
    minHeight: undefined,
  },
  loginSheetInner: {
    paddingBottom: sh(8),
  },
  loginLogoWrap: {
    alignItems: 'center',
    marginBottom: sh(24),
  },
  loginTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: sh(24),
    minHeight: sh(46),
  },
  loginBackButtonTop: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    paddingHorizontal: sw(4),
    zIndex: 1,
  },
  loginLogoWrapInBar: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginLogoImage: {
    width: sw(168),
    height: sw(46),
  },
  loginGoogleTitle: {
    fontSize: ms(28),
    fontWeight: '700',
    color: '#202124',
    letterSpacing: 0,
    marginBottom: sh(4),
    textAlign: 'left',
  },
  loginGoogleSubtitle: {
    fontSize: ms(16),
    fontWeight: '400',
    color: Colors.textSecondary,
    lineHeight: ms(22),
    marginBottom: sh(28),
    textAlign: 'left',
  },
  loginGoogleSubtitleCompact: {
    marginBottom: sh(16),
  },
  loginFormBlock: {
    width: '100%',
  },
  loginActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: sh(32),
    marginBottom: sh(16),
  },
  loginAccountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sw(14),
    marginBottom: sh(20),
    paddingVertical: sh(10),
    paddingHorizontal: sw(12),
    backgroundColor: Colors.surfaceLight,
    borderRadius: sw(12),
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  loginAccountAvatar: {
    width: sw(44),
    height: sw(44),
    borderRadius: sw(22),
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.primaryLight + '55',
  },
  loginAccountAvatarText: {
    fontSize: ms(18),
    fontWeight: '700',
    color: Colors.textOnPrimary,
  },
  loginAccountEmail: {
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  loginAccountHint: {
    fontSize: ms(12),
    color: Colors.textSecondary,
    marginTop: sh(2),
  },
  loginFooterLinks: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: sw(20),
    marginTop: sh(24),
    paddingTop: sh(8),
    paddingBottom: sh(4),
  },
  loginFooterLink: {
    fontSize: ms(12),
    fontWeight: '400',
    color: Colors.textSecondary,
  },
  loginStepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(8),
    marginBottom: sh(24),
  },
  loginStepDot: {
    width: sw(8),
    height: sw(8),
    borderRadius: sw(4),
    backgroundColor: Colors.googleBorder,
  },
  loginStepDotActive: {
    width: sw(24),
    backgroundColor: Colors.googleBlue,
  },
  loginStepLabel: {
    fontSize: ms(12),
    color: Colors.googleGrayLight,
    fontWeight: '500',
    marginLeft: sw(4),
  },
  loginCard: {
    backgroundColor: Colors.white,
    borderRadius: sw(8),
    borderWidth: 1,
    borderColor: Colors.googleBorder,
    padding: sw(20),
    marginBottom: sh(16),
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  loginCardTitle: {
    fontSize: ms(16),
    fontWeight: '500',
    color: '#202124',
    marginBottom: sh(4),
  },
  loginCardHint: {
    fontSize: ms(13),
    fontWeight: '400',
    color: Colors.googleGray,
    lineHeight: ms(18),
    marginBottom: sh(20),
  },
  loginFieldWrap: {
    marginBottom: sh(16),
  },
  loginFieldButtonGroup: {
    width: '100%',
    flexDirection: 'column',
    marginBottom: sh(16),
  },
  loginFieldLabel: {
    fontSize: ms(14),
    fontWeight: '700',
    color: '#202124',
    marginBottom: sh(8),
  },
  loginInputOutlined: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#B8D4E8',
    borderRadius: sw(8),
    backgroundColor: '#F5F7FA',
    paddingHorizontal: sw(14),
    minHeight: sh(52),
  },
  loginInputOutlinedFocused: {
    borderColor: Colors.primary,
    borderWidth: 1.5,
    backgroundColor: Colors.background,
  },
  loginInputInner: {
    flex: 1,
    fontSize: ms(16),
    color: Colors.textPrimary,
    paddingVertical: sh(12),
    fontWeight: '400',
  },
  loginInputIcon: {
    marginRight: sw(12),
  },
  loginOtpActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: sh(8),
    marginBottom: sh(4),
    gap: sw(12),
  },
  loginTextButton: {
    paddingVertical: sh(8),
  },
  loginTextButtonLabel: {
    fontSize: ms(14),
    fontWeight: '700',
    color: Colors.primary,
  },
  loginPrimaryButton: {
    backgroundColor: Colors.primary,
    borderRadius: sw(8),
    minHeight: sh(52),
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    marginTop: sh(20),
  },
  loginPrimaryButtonDisabled: {
    backgroundColor: '#A8D4E8',
  },
  loginPrimaryButtonText: {
    fontSize: ms(16),
    fontWeight: '600',
    color: Colors.textOnPrimary,
    letterSpacing: 0.25,
  },
  loginPrimaryButtonTextDisabled: {
    color: Colors.textMuted,
  },
  loginOtpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: sw(6),
    marginBottom: sh(12),
  },
  loginOtpBox: {
    flex: 1,
    maxWidth: sw(48),
    aspectRatio: 0.85,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    borderRadius: sw(12),
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginOtpBoxFilled: {
    borderColor: Colors.primary,
    backgroundColor: Colors.surfaceLight,
  },
  loginOtpBoxText: {
    fontSize: ms(22),
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  loginOtpHiddenInput: {
    position: 'absolute',
    opacity: 0,
    width: 1,
    height: 1,
  },
  loginVerifiedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sw(8),
    backgroundColor: Colors.surfaceAccent,
    borderRadius: sw(20),
    paddingVertical: sh(8),
    paddingHorizontal: sw(14),
    marginBottom: sh(16),
    alignSelf: 'stretch',
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  loginVerifiedChipText: {
    fontSize: ms(13),
    fontWeight: '600',
    color: Colors.primaryDark,
    flexShrink: 1,
  },
  loginDivider: {
    height: 1,
    backgroundColor: Colors.googleBorder,
    marginVertical: sh(16),
  },
  loginFooterNote: {
    fontSize: ms(13),
    color: Colors.textMuted,
    textAlign: 'center',
    lineHeight: ms(18),
    paddingHorizontal: sw(8),
    marginTop: sh(8),
  },
  loginBackLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sw(4),
    marginBottom: sh(16),
    paddingVertical: sh(4),
  },
  loginBackLinkText: {
    fontSize: ms(14),
    fontWeight: '700',
    color: Colors.primary,
  },

  /* legacy aliases used elsewhere */
  loginHeaderBand: { paddingTop: sh(16), alignItems: 'center' },
  loginHeaderTitle: { fontSize: ms(24), fontWeight: '400', color: '#202124' },
  loginFormCard: { flex: 1, backgroundColor: Colors.white },
  loginScrollContentLegacy: { flexGrow: 1 },
  loginLabel: { fontSize: ms(12), fontWeight: '500', color: Colors.googleGray, marginBottom: sh(6) },
  loginInput: {
    borderWidth: 1,
    borderColor: Colors.googleBorder,
    borderRadius: sw(4),
    paddingVertical: sh(12),
    paddingHorizontal: sw(14),
    fontSize: ms(16),
    color: '#202124',
    backgroundColor: Colors.white,
  },
  loginSendOtp: { alignSelf: 'flex-end', marginTop: sh(8), paddingVertical: sh(8) },
  loginSendOtpText: { fontSize: ms(14), fontWeight: '500', color: Colors.googleBlue },
  loginSubmitButton: {
    backgroundColor: Colors.googleBlue,
    paddingVertical: sh(14),
    borderRadius: sw(24),
    alignItems: 'center',
    marginTop: sh(8),
  },
  loginSubmitText: { fontSize: ms(15), fontWeight: '500', color: Colors.white },
  loginSecureNote: { fontSize: ms(12), color: Colors.googleGrayLight, textAlign: 'center' },
  loginSectionCard: {
    borderWidth: 1,
    borderColor: Colors.googleBorder,
    borderRadius: sw(8),
    padding: sw(20),
    marginBottom: sh(16),
    backgroundColor: Colors.white,
  },
  loginSectionTitle: { fontSize: ms(16), fontWeight: '500', color: '#202124', marginBottom: sh(4) },
  loginSectionSubtitle: { fontSize: ms(13), color: Colors.googleGray, marginBottom: sh(16) },
  loginVerifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sw(8),
    paddingVertical: sh(8),
    paddingHorizontal: sw(14),
    backgroundColor: '#E6F4EA',
    borderRadius: sw(20),
    marginBottom: sh(14),
  },
  loginVerifiedText: { fontSize: ms(13), fontWeight: '500', color: Colors.googleGreen },
  loginGoogleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(10),
    paddingVertical: sh(12),
    borderRadius: sw(24),
    borderWidth: 1,
    borderColor: Colors.googleBorder,
    backgroundColor: Colors.white,
  },
  loginGoogleButtonText: { fontSize: ms(15), fontWeight: '500', color: '#3C4043' },
  loginOrDivider: { flexDirection: 'row', alignItems: 'center', marginVertical: sh(16) },
  loginOrLine: { flex: 1, height: 1, backgroundColor: Colors.googleBorder },
  loginOrText: { fontSize: ms(13), color: Colors.googleGray, paddingHorizontal: sw(12) },

  profileContainer: {
    flex: 1,
    backgroundColor: Colors.background,
    paddingHorizontal: sw(24),
    paddingTop: sh(32),
  },
  profileHeader: { alignItems: 'center', marginBottom: sh(32) },
  profileAvatar: {
    width: sw(88),
    height: sw(88),
    borderRadius: sw(44),
    backgroundColor: Colors.surfaceAccent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: sh(16),
    borderWidth: 3,
    borderColor: Colors.primary + '25',
  },
  profileAvatarText: { fontSize: ms(32), fontWeight: '700', color: Colors.primary },
  profileName: { fontSize: ms(22), fontWeight: '700', color: Colors.textPrimary, marginBottom: sh(4) },
  profileMobile: { fontSize: ms(15), color: Colors.textSecondary },
  profileCard: {
    backgroundColor: Colors.surfaceLight,
    borderRadius: sw(20),
    padding: sw(24),
    marginBottom: sh(20),
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  profileCardTitle: {
    fontSize: ms(13),
    fontWeight: '600',
    color: Colors.textMuted,
    marginBottom: sh(8),
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  profileLogoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(10),
    marginTop: sh(32),
    paddingVertical: sh(16),
    paddingHorizontal: sw(24),
    backgroundColor: Colors.surface,
    borderRadius: sw(16),
    borderWidth: 1.5,
    borderColor: Colors.border,
  },
  profileLogoutText: { fontSize: ms(16), fontWeight: '600', color: Colors.primaryDark },
});
