import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/theme';
import { type Scalers } from '@/utils/responsive';

/**
 * Auth screens styles (Login, Register, OTP).
 */
export const authStyles = ({ sw, sh, ms }: Scalers) => StyleSheet.create({
  welcomeContainer: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  welcomeGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: sh(160),
    backgroundColor: 'rgba(0, 42, 64, 0.5)',
  },
  welcomeContentCard: {
    paddingHorizontal: sw(28),
    paddingTop: sh(28),
    paddingBottom: sh(32),
    backgroundColor: Colors.background,
    borderTopLeftRadius: sw(28),
    borderTopRightRadius: sw(28),
    shadowColor: Colors.primaryDark,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: sw(16),
    elevation: 8,
  },
  welcomeDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: sw(10),
    marginBottom: sh(24),
  },
  welcomeDot: {
    height: sh(8),
    borderRadius: sw(4),
    backgroundColor: Colors.border,
  },
  welcomeDotActive: {
    width: sw(24),
    backgroundColor: Colors.primary,
  },
  welcomeTitle: {
    fontSize: ms(26),
    fontWeight: '800',
    color: Colors.textPrimary,
    textAlign: 'center',
    marginBottom: sh(8),
    letterSpacing: -0.5,
  },
  welcomeSubtitle: {
    fontSize: ms(15),
    color: Colors.textSecondary,
    textAlign: 'center',
    marginBottom: sh(28),
    lineHeight: ms(22),
  },
  welcomeButton: {
    backgroundColor: Colors.primary,
    paddingVertical: sh(18),
    borderRadius: sw(16),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: sw(8),
    elevation: 4,
  },
  welcomeButtonText: {
    fontSize: ms(17),
    fontWeight: '700',
    color: Colors.textOnPrimary,
    letterSpacing: 0.3,
  },
  loginScrollContent: {
    flexGrow: 1,
    paddingBottom: sh(32),
  },
  loginHeaderBand: {
    paddingTop: sh(48),
    paddingBottom: sh(32),
    paddingHorizontal: sw(24),
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginHeaderLogoWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: sh(12),
  },
  loginHeaderLogoImage: {
    width: sw(160),
    height: sw(42),
  },
  loginHeaderTitle: {
    fontSize: ms(24),
    fontWeight: '800',
    color: Colors.textOnPrimary,
    letterSpacing: -0.5,
  },
  loginFormCard: {
    flex: 1,
    backgroundColor: Colors.background,
    borderTopLeftRadius: sw(28),
    borderTopRightRadius: sw(28),
    paddingHorizontal: sw(24),
    paddingTop: sh(28),
    paddingBottom: sh(32),
    marginTop: -sh(20),
    shadowColor: Colors.primaryDark,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: sw(16),
    elevation: 8,
  },
  loginCardTitle: {
    fontSize: ms(24),
    fontWeight: '800',
    color: Colors.textPrimary,
    marginBottom: sh(8),
  },
  loginCardSubtitle: {
    fontSize: ms(15),
    color: Colors.textSecondary,
    marginBottom: sh(24),
    lineHeight: ms(22),
  },
  loginCard: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    marginBottom: 0,
  },
  loginLogoWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: sh(24),
  },
  loginLogoImage: {
    width: sw(180),
    height: sw(48),
  },
  loginTitle: {
    fontSize: ms(26),
    fontWeight: '800',
    color: Colors.textPrimary,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  loginSubtitle: {
    fontSize: ms(15),
    color: Colors.textSecondary,
    textAlign: 'center',
    marginTop: sh(8),
  },
  loginLabel: {
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.textPrimary,
    marginBottom: sh(8),
  },
  loginInput: {
    borderWidth: 1,
    borderColor: Colors.borderLight,
    borderRadius: sw(12),
    paddingVertical: sh(14),
    paddingHorizontal: sw(16),
    fontSize: ms(16),
    color: Colors.textPrimary,
    backgroundColor: Colors.surface,
  },
  loginSendOtp: {
    alignSelf: 'flex-end',
    marginTop: sh(8),
    marginBottom: sh(16),
    paddingVertical: sh(8),
    paddingHorizontal: 0,
    backgroundColor: 'transparent',
  },
  loginSendOtpText: {
    fontSize: ms(14),
    fontWeight: '700',
    color: Colors.primary,
  },
  loginSubmitButton: {
    backgroundColor: Colors.primary,
    paddingVertical: sh(16),
    borderRadius: sw(12),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: sh(8),
  },
  loginSubmitText: {
    fontSize: ms(17),
    fontWeight: '700',
    color: Colors.textOnPrimary,
    letterSpacing: 0.3,
  },
  loginToggleWrap: {
    marginTop: sh(24),
    alignItems: 'center',
    paddingVertical: sh(12),
  },
  loginToggleText: {
    fontSize: ms(15),
    color: Colors.textSecondary,
  },
  loginToggleLink: {
    fontWeight: '700',
    color: Colors.primary,
  },
  loginOrDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: sh(20),
    marginBottom: sh(16),
  },
  loginOrLine: {
    flex: 1,
    height: 1,
    backgroundColor: Colors.borderLight,
  },
  loginOrText: {
    fontSize: ms(14),
    color: Colors.textMuted,
    paddingHorizontal: sw(16),
  },
  loginSecureNote: {
    fontSize: ms(13),
    color: Colors.textMuted,
    textAlign: 'center',
  },
  profileContainer: {
    flex: 1,
    backgroundColor: Colors.background,
    paddingHorizontal: sw(24),
    paddingTop: sh(32),
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: sh(32),
  },
  profileAvatar: {
    width: sw(88),
    height: sw(88),
    borderRadius: sw(44),
    backgroundColor: Colors.surfaceAccent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: sh(16),
    borderWidth: 3,
    borderColor: Colors.primary + '25',
  },
  profileAvatarText: {
    fontSize: ms(32),
    fontWeight: '700',
    color: Colors.primary,
  },
  profileName: {
    fontSize: ms(22),
    fontWeight: '700',
    color: Colors.textPrimary,
    marginBottom: sh(4),
  },
  profileMobile: {
    fontSize: ms(15),
    color: Colors.textSecondary,
  },
  profileCard: {
    backgroundColor: Colors.surfaceLight,
    borderRadius: sw(20),
    padding: sw(24),
    marginBottom: sh(20),
    borderWidth: 1,
    borderColor: Colors.borderLight,
    shadowColor: Colors.primaryDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: sw(12),
    elevation: 2,
  },
  profileCardTitle: {
    fontSize: ms(13),
    fontWeight: '600',
    color: Colors.textMuted,
    marginBottom: sh(8),
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  profileLogoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(10),
    marginTop: sh(32),
    paddingVertical: sh(16),
    paddingHorizontal: sw(24),
    backgroundColor: Colors.surface,
    borderRadius: sw(16),
    borderWidth: 1.5,
    borderColor: Colors.border,
  },
  profileLogoutText: {
    fontSize: ms(16),
    fontWeight: '600',
    color: Colors.primaryDark,
  },
});
