import { StyleSheet } from 'react-native';

import { Colors } from '@/constants/theme';
import { ms, sh, sw } from '@/utils/responsive';

/** Google Material — book a call */
export const bookingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  scrollContent: {
    paddingHorizontal: sw(16),
    paddingTop: sh(8),
    paddingBottom: sh(40),
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sw(14),
    marginBottom: sh(16),
  },
  heroIconWrap: {
    width: sw(48),
    height: sw(48),
    borderRadius: sw(24),
    backgroundColor: '#e8f0fe',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  heroText: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    fontSize: ms(22),
    fontWeight: '500',
    color: '#202124',
    letterSpacing: -0.2,
    marginBottom: sh(4),
  },
  subtitle: {
    fontSize: ms(14),
    fontWeight: '400',
    color: '#5f6368',
    lineHeight: ms(20),
  },
  googleCard: {
    backgroundColor: Colors.white,
    borderRadius: sw(8),
    borderWidth: 1,
    borderColor: '#e8eaed',
    overflow: 'hidden',
    marginBottom: sh(16),
  },
  sectionLabel: {
    fontSize: ms(11),
    fontWeight: '600',
    color: '#80868b',
    letterSpacing: 0.5,
    paddingHorizontal: sw(16),
    paddingTop: sh(14),
    paddingBottom: sh(6),
  },
  fieldBlock: {
    paddingHorizontal: sw(16),
    paddingVertical: sh(10),
  },
  fieldLabel: {
    fontSize: ms(12),
    fontWeight: '500',
    color: '#5f6368',
    marginBottom: sh(6),
  },
  input: {
    fontSize: ms(16),
    fontWeight: '400',
    color: '#202124',
    paddingVertical: sh(4),
    paddingHorizontal: 0,
    minHeight: sh(28),
  },
  inputMultiline: {
    minHeight: sh(88),
    textAlignVertical: 'top',
    lineHeight: ms(22),
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#e8eaed',
  },
  dividerInset: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#e8eaed',
    marginLeft: sw(16),
  },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: sh(12),
    paddingHorizontal: sw(16),
    gap: sw(14),
  },
  listIconWrap: {
    width: sw(40),
    height: sw(40),
    borderRadius: sw(8),
    backgroundColor: '#e8f0fe',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  listIconWrapGreen: {
    backgroundColor: '#e6f4ea',
  },
  listBody: {
    flex: 1,
    minWidth: 0,
  },
  listTitle: {
    fontSize: ms(14),
    fontWeight: '500',
    color: '#202124',
  },
  listSub: {
    fontSize: ms(12),
    fontWeight: '400',
    color: '#5f6368',
    marginTop: sh(2),
    lineHeight: ms(16),
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: sw(8),
    paddingHorizontal: sw(16),
    paddingBottom: sh(12),
  },
  chip: {
    paddingHorizontal: sw(12),
    paddingVertical: sh(6),
    borderRadius: sw(16),
    backgroundColor: '#f1f3f4',
    borderWidth: 1,
    borderColor: '#e8eaed',
  },
  chipSelected: {
    backgroundColor: '#e8f0fe',
    borderColor: '#1a73e8',
  },
  chipText: {
    fontSize: ms(13),
    fontWeight: '500',
    color: '#5f6368',
  },
  chipTextSelected: {
    color: '#1967d2',
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sw(10),
    backgroundColor: '#e8f0fe',
    borderRadius: sw(8),
    paddingHorizontal: sw(14),
    paddingVertical: sh(12),
    marginBottom: sh(16),
  },
  infoBannerText: {
    flex: 1,
    fontSize: ms(13),
    fontWeight: '400',
    color: '#1967d2',
    lineHeight: ms(18),
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sw(10),
    backgroundColor: '#fce8e6',
    borderRadius: sw(8),
    paddingHorizontal: sw(14),
    paddingVertical: sh(12),
    marginBottom: sh(16),
  },
  errorText: {
    flex: 1,
    fontSize: ms(13),
    fontWeight: '400',
    color: '#c5221f',
    lineHeight: ms(18),
  },
  successCard: {
    backgroundColor: Colors.white,
    borderRadius: sw(8),
    borderWidth: 1,
    borderColor: '#e8eaed',
    alignItems: 'center',
    paddingVertical: sh(28),
    paddingHorizontal: sw(20),
    marginBottom: sh(16),
  },
  tickRing: {
    position: 'absolute',
    width: sw(88),
    height: sw(88),
    borderRadius: sw(44),
    backgroundColor: 'rgba(24, 128, 56, 0.15)',
    borderWidth: 2,
    borderColor: 'rgba(24, 128, 56, 0.35)',
  },
  tickIconWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  successTitle: {
    fontSize: ms(18),
    fontWeight: '500',
    color: '#202124',
    marginTop: sh(16),
    textAlign: 'center',
  },
  successSub: {
    fontSize: ms(14),
    fontWeight: '400',
    color: '#5f6368',
    marginTop: sh(8),
    textAlign: 'center',
    lineHeight: ms(20),
  },
  primaryBtn: {
    backgroundColor: '#1a73e8',
    borderRadius: sw(8),
    minHeight: sh(48),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: sh(4),
  },
  primaryBtnDisabled: {
    opacity: 0.55,
  },
  primaryBtnPressed: {
    opacity: 0.88,
  },
  primaryBtnText: {
    fontSize: ms(14),
    fontWeight: '600',
    color: '#ffffff',
  },
  secondaryBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: sh(14),
    marginTop: sh(4),
  },
  secondaryBtnText: {
    fontSize: ms(14),
    fontWeight: '600',
    color: '#1a73e8',
  },
});
