import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/theme';
import { ms, sh, sw } from '@/utils/responsive';

export const companyRegistrationUploadTrackingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f7fa',
  },
  scrollContent: {
    padding: sw(20),
    paddingBottom: sh(48),
  },
  loadingWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f0f7fa',
    gap: sh(12),
  },
  loadingText: {
    fontSize: ms(15),
    color: Colors.textMuted,
  },
  headerCard: {
    backgroundColor: Colors.white,
    borderRadius: sw(16),
    padding: sw(20),
    marginBottom: sh(20),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.borderLight,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  headerIconWrap: {
    width: sw(52),
    height: sw(52),
    borderRadius: sw(26),
    backgroundColor: Colors.surfaceAccent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: sh(12),
  },
  headerTitle: {
    fontSize: ms(20),
    fontWeight: '700',
    color: Colors.textPrimary,
    marginBottom: sh(6),
  },
  headerSubtitle: {
    fontSize: ms(13),
    color: Colors.textMuted,
    textAlign: 'center',
  },
  rejectedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sw(10),
    backgroundColor: '#fef2f2',
    borderRadius: sw(12),
    padding: sw(14),
    marginBottom: sh(16),
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  rejectedText: {
    flex: 1,
    fontSize: ms(14),
    fontWeight: '600',
    color: '#b91c1c',
  },
  timelineCard: {
    backgroundColor: Colors.white,
    borderRadius: sw(16),
    paddingVertical: sh(8),
    paddingLeft: sw(8),
    paddingRight: sw(20),
    marginBottom: sh(20),
    borderWidth: 1,
    borderColor: Colors.borderLight,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  stepWrap: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: sh(4),
  },
  stepLeft: {
    alignItems: 'center',
    width: sw(40),
  },
  stepCircle: {
    width: sw(36),
    height: sw(36),
    borderRadius: sw(18),
    backgroundColor: Colors.surfaceLight,
    borderWidth: 2,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepCircleDone: {
    backgroundColor: '#22c55e',
    borderColor: '#22c55e',
  },
  stepCircleCurrent: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  stepNumber: {
    fontSize: ms(14),
    fontWeight: '700',
    color: Colors.textMuted,
  },
  stepLine: {
    width: 2,
    flex: 1,
    minHeight: sh(28),
    backgroundColor: Colors.borderLight,
    marginVertical: sh(2),
  },
  stepLineDone: {
    backgroundColor: '#22c55e',
  },
  stepContent: {
    flex: 1,
    paddingLeft: sw(12),
    paddingBottom: sh(20),
  },
  stepLabel: {
    fontSize: ms(16),
    fontWeight: '700',
    color: Colors.textPrimary,
    marginBottom: sh(2),
  },
  stepLabelPending: {
    color: Colors.textMuted,
    fontWeight: '600',
  },
  stepSublabel: {
    fontSize: ms(13),
    color: Colors.textMuted,
  },
  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(8),
    backgroundColor: Colors.primary,
    borderRadius: sw(14),
    paddingVertical: sh(14),
    paddingHorizontal: sw(24),
  },
  refreshBtnText: {
    color: Colors.textOnPrimary,
    fontSize: ms(15),
    fontWeight: '700',
  },
  docSection: {
    backgroundColor: Colors.white,
    borderRadius: sw(16),
    padding: sw(20),
    marginBottom: sh(20),
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  docSectionTitle: {
    fontSize: ms(18),
    fontWeight: '700',
    color: Colors.textPrimary,
    marginBottom: sh(16),
  },
  directorHeader: {
    fontSize: ms(16),
    fontWeight: '600',
    color: Colors.textPrimary,
    marginTop: sh(10),
    marginBottom: sh(12),
  },
  docCardRow: {
    flexDirection: 'row',
    gap: sw(12),
    marginBottom: sh(16),
  },
  docCard: {
    flex: 1,
    backgroundColor: Colors.surfaceLight,
    borderRadius: sw(12),
    borderWidth: 1,
    borderColor: Colors.borderLight,
    overflow: 'hidden',
  },
  docPreviewWrap: {
    height: sh(100),
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docPreviewImg: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  docInfo: {
    padding: sw(10),
  },
  docLabel: {
    fontSize: ms(13),
    fontWeight: '600',
    color: Colors.textPrimary,
    marginBottom: sh(8),
  },
  docDownloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(6),
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: sw(8),
    paddingVertical: sh(6),
  },
  docDownloadText: {
    fontSize: ms(12),
    fontWeight: '600',
    color: Colors.primaryDark,
  },
});
