import { Platform, StyleSheet } from 'react-native';

import { Colors } from '@/constants/theme';
import { ms, sh, sw } from '@/utils/responsive';

/** Google Material — Review & payment screen */
export const reviewPaywallStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: sw(20),
    paddingTop: sh(8),
    paddingBottom: sh(16),
  },

  header: {
    paddingBottom: sh(12),
    alignItems: 'center',
    width: '100%',
  },
  headerCenterCol: {
    width: '100%',
    alignItems: 'center',
    marginBottom: sh(4),
  },
  caseIdInline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginTop: sh(10),
    maxWidth: '100%',
    paddingHorizontal: sw(8),
    gap: sw(6),
  },
  caseIdInlineLabel: {
    fontSize: ms(12),
    fontWeight: '500',
    color: '#80868b',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  caseIdInlineSep: {
    fontSize: ms(12),
    color: '#dadce0',
    fontWeight: '600',
  },
  caseIdInlineValue: {
    fontSize: ms(14),
    fontWeight: '600',
    color: '#202124',
    flexShrink: 1,
  },
  headerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sw(5),
    backgroundColor: '#e6f4ea',
    paddingHorizontal: sw(10),
    paddingVertical: sh(5),
    borderRadius: sw(16),
    flexShrink: 0,
  },
  headerBadgeText: {
    fontSize: ms(12),
    fontWeight: '600',
    color: '#188038',
  },
  headerSub: {
    fontSize: ms(14),
    fontWeight: '400',
    color: Colors.textSecondary,
    lineHeight: ms(21),
    marginTop: sh(10),
    textAlign: 'left',
    width: '100%',
  },

  card: {
    backgroundColor: Colors.background,
    borderRadius: sw(8),
    marginBottom: sh(12),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e8eaed',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: sw(16),
    paddingTop: sh(14),
    paddingBottom: sh(8),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e8eaed',
  },
  cardTitle: {
    fontSize: ms(16),
    fontWeight: '700',
    color: '#202124',
  },
  cardHint: {
    fontSize: ms(11),
    fontWeight: '500',
    color: '#80868b',
  },

  emptyText: {
    padding: sw(16),
    fontSize: ms(14),
    color: Colors.textSecondary,
    lineHeight: ms(21),
  },

  docsRow: {
    flexDirection: 'row',
    gap: sw(12),
    paddingHorizontal: sw(16),
    paddingTop: sh(8),
    paddingBottom: sh(12),
  },
  docItem: { flex: 1 },
  docLabel: {
    fontSize: ms(12),
    fontWeight: '600',
    color: '#5f6368',
    marginBottom: sh(6),
  },

  uploadStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    backgroundColor: '#F5F7FA',
    paddingHorizontal: sw(16),
    paddingVertical: sh(10),
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#e8eaed',
  },
  uploadDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: sw(5),
  },
  uploadDotGreen: { backgroundColor: '#188038' },
  uploadDotRed: { backgroundColor: '#d93025' },
  uploadStatusText: {
    fontSize: ms(12),
    color: '#5f6368',
  },

  paySummaryBody: {
    paddingHorizontal: sw(16),
    paddingBottom: sh(14),
    paddingTop: sh(4),
  },
  paySummaryTitle: {
    fontSize: ms(15),
    fontWeight: '600',
    color: '#202124',
    marginBottom: sh(4),
  },
  paySummaryDesc: {
    fontSize: ms(13),
    color: Colors.textSecondary,
    lineHeight: ms(19),
    marginBottom: sh(12),
  },
  payBreakdown: {
    backgroundColor: '#f8f9fa',
    borderRadius: sw(8),
    borderWidth: 1,
    borderColor: '#e8eaed',
    paddingHorizontal: sw(14),
    paddingVertical: sh(4),
    marginTop: sh(4),
    marginBottom: sh(4),
  },
  payBreakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: sh(10),
  },
  payBreakdownLabel: {
    fontSize: ms(14),
    fontWeight: '400',
    color: '#5f6368',
  },
  payBreakdownValue: {
    fontSize: ms(14),
    fontWeight: '500',
    color: '#202124',
  },
  payBreakdownTotalRow: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#e8eaed',
    marginTop: sh(2),
    paddingTop: sh(12),
    paddingBottom: sh(6),
  },
  payBreakdownTotalLabel: {
    fontSize: ms(15),
    fontWeight: '600',
    color: '#202124',
  },
  payBreakdownTotalValue: {
    fontSize: ms(18),
    fontWeight: '700',
    color: '#1a73e8',
    letterSpacing: -0.2,
  },
  gatewayWarn: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sw(8),
    backgroundColor: '#fce8e6',
    padding: sw(12),
    borderRadius: sw(8),
    marginTop: sh(4),
    borderWidth: 1,
    borderColor: '#f5c6c2',
  },
  gatewayWarnText: {
    flex: 1,
    fontSize: ms(12),
    color: '#c5221f',
    lineHeight: ms(17),
  },
  dashboardHint: {
    fontSize: ms(12),
    color: '#80868b',
    marginTop: sh(8),
  },

  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sw(10),
    paddingHorizontal: sw(16),
    paddingVertical: sh(8),
  },
  infoText: {
    fontSize: ms(14),
    color: '#202124',
    flex: 1,
    lineHeight: ms(20),
  },

  lockCardIntro: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sw(14),
    paddingHorizontal: sw(16),
    paddingTop: sh(14),
    paddingBottom: sh(12),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e8eaed',
  },
  lockIntroIconWrap: {
    width: sw(40),
    height: sw(40),
    borderRadius: sw(20),
    backgroundColor: '#f1f3f4',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  lockIntroText: {
    flex: 1,
    minWidth: 0,
  },
  lockCardSub: {
    fontSize: ms(13),
    fontWeight: '400',
    color: '#5f6368',
    lineHeight: ms(19),
    marginTop: sh(4),
  },
  lockList: {
    paddingBottom: sh(4),
  },
  lockListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: sw(16),
    paddingVertical: sh(12),
    gap: sw(14),
  },
  lockFeatureIconWrap: {
    width: sw(40),
    height: sw(40),
    borderRadius: sw(8),
    backgroundColor: '#e8f0fe',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  lockListContent: {
    flex: 1,
    minWidth: 0,
  },
  lockListLabel: {
    fontSize: ms(14),
    fontWeight: '500',
    color: '#202124',
    letterSpacing: 0.1,
  },
  lockListDesc: {
    fontSize: ms(12),
    fontWeight: '400',
    color: '#5f6368',
    marginTop: sh(2),
    lineHeight: ms(16),
  },
  lockListDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#e8eaed',
    marginLeft: sw(70),
  },

  rzpInfoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sw(8),
    paddingHorizontal: sw(16),
    paddingBottom: sh(10),
  },
  rzpInfoText: {
    fontSize: ms(13),
    color: Colors.textSecondary,
    flex: 1,
    lineHeight: ms(19),
  },
  rzpMethodRow: {
    flexDirection: 'row',
    gap: sw(8),
    paddingHorizontal: sw(16),
    paddingBottom: sh(12),
    flexWrap: 'wrap',
  },
  rzpMethodChip: {
    backgroundColor: '#F5F7FA',
    paddingHorizontal: sw(12),
    paddingVertical: sh(6),
    borderRadius: sw(16),
    borderWidth: 1,
    borderColor: '#e8eaed',
  },
  rzpMethodText: {
    fontSize: ms(12),
    color: '#202124',
    fontWeight: '500',
  },
  rzpBadgeRow: {
    paddingHorizontal: sw(16),
    paddingBottom: sh(14),
  },
  rzpBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#F5F7FA',
    paddingHorizontal: sw(10),
    paddingVertical: sh(5),
    borderRadius: sw(16),
    borderWidth: 1,
    borderColor: '#e8eaed',
  },
  rzpBadgeText: {
    fontSize: ms(11),
    color: '#5f6368',
    fontWeight: '500',
  },

  footer: {
    borderTopWidth: 1,
    borderTopColor: '#e8eaed',
    backgroundColor: Colors.background,
    paddingHorizontal: sw(20),
    paddingTop: sh(12),
    paddingBottom: Platform.OS === 'ios' ? sh(28) : sh(16),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 8,
  },
  footerAmountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: sh(12),
    paddingVertical: sh(10),
    paddingHorizontal: sw(14),
    backgroundColor: '#F5F7FA',
    borderRadius: sw(8),
    borderWidth: 1,
    borderColor: '#e8eaed',
  },
  footerAmountLabel: {
    fontSize: ms(14),
    fontWeight: '500',
    color: '#5f6368',
  },
  footerAmountValue: {
    fontSize: ms(20),
    fontWeight: '700',
    color: Colors.primary,
  },
  payBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(8),
    backgroundColor: Colors.primary,
    minHeight: sh(52),
    borderRadius: sw(8),
    width: '100%',
  },
  payBtnDisabled: { opacity: 0.65 },
  payBtnText: {
    fontSize: ms(16),
    fontWeight: '600',
    color: Colors.textOnPrimary,
    letterSpacing: 0.25,
  },
  secureFooter: {
    marginTop: sh(10),
    alignItems: 'center',
    width: '100%',
  },
  secureNote: {
    textAlign: 'center',
    fontSize: ms(11),
    color: '#80868b',
    lineHeight: ms(16),
    paddingHorizontal: sw(4),
  },
  rzpPoweredRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(6),
    marginTop: sh(8),
  },
  rzpPoweredText: {
    fontSize: ms(11),
    fontWeight: '600',
    color: '#3395FF',
    letterSpacing: 0.2,
  },
});

export const reviewTableStyles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: sw(16),
    paddingVertical: sh(12),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e8eaed',
    gap: sw(8),
  },
  rowLabel: {
    fontSize: ms(13),
    color: '#5f6368',
    fontWeight: '500',
    width: sw(112),
    flexShrink: 0,
    paddingTop: sh(2),
  },
  rowValueWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: sw(8),
  },
  rowValue: {
    flex: 1,
    fontSize: ms(14),
    color: '#202124',
    fontWeight: '400',
    lineHeight: ms(20),
  },
  editBtn: {
    padding: sh(2),
    marginTop: sh(-2),
  },
});

export const reviewThumbStyles = StyleSheet.create({
  wrap: {
    borderRadius: sw(8),
    overflow: 'hidden',
    backgroundColor: '#F5F7FA',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#e8eaed',
  },
  img: { width: '100%', height: '100%' },
  overlay: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 6,
    padding: 3,
  },
  pdfBadge: { alignItems: 'center', gap: 4 },
  pdfText: { fontSize: ms(11), fontWeight: '700', color: '#d93025' },
  label: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.55)',
    color: '#fff',
    fontSize: ms(10),
    fontWeight: '600',
    textAlign: 'center',
    paddingVertical: 3,
  },
  missing: {
    alignItems: 'center',
    gap: 4,
    padding: sw(16),
    borderRadius: sw(8),
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#dadce0',
    backgroundColor: '#F5F7FA',
    aspectRatio: 1,
    justifyContent: 'center',
  },
  missingText: { fontSize: ms(10), color: '#80868b' },
  lightboxBg: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxImg: { width: '92%', height: '75%' },
  lightboxClose: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 56 : 24,
    right: 20,
  },
});

export const reviewEditStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: Colors.background,
    borderTopLeftRadius: sw(16),
    borderTopRightRadius: sw(16),
    paddingHorizontal: sw(20),
    paddingBottom: Platform.OS === 'ios' ? sh(36) : sh(24),
    paddingTop: sh(12),
  },
  handle: {
    width: sw(36),
    height: sh(4),
    borderRadius: 2,
    backgroundColor: '#dadce0',
    alignSelf: 'center',
    marginBottom: sh(16),
  },
  title: {
    fontSize: ms(20),
    fontWeight: '700',
    color: '#202124',
    marginBottom: sh(16),
  },
  saveBtn: {
    backgroundColor: Colors.primary,
    minHeight: sh(52),
    borderRadius: sw(8),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: sh(8),
    marginBottom: sh(10),
  },
  saveText: {
    fontSize: ms(16),
    fontWeight: '600',
    color: Colors.textOnPrimary,
  },
  cancelBtn: {
    alignItems: 'center',
    paddingVertical: sh(12),
  },
  cancelText: {
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.primary,
  },
});

export const reviewRzpStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: sw(16),
    paddingTop: Platform.OS === 'ios' ? sh(56) : sh(24),
    paddingBottom: sh(12),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e8eaed',
    backgroundColor: Colors.background,
  },
  headerLeft: { flex: 1 },
  headerTitle: {
    fontSize: ms(18),
    fontWeight: '700',
    color: '#202124',
  },
  headerSub: {
    fontSize: ms(12),
    color: '#5f6368',
    marginTop: sh(2),
  },
  closeBtn: {
    width: sw(40),
    height: sw(40),
    borderRadius: sw(20),
    backgroundColor: '#F5F7FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secureBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sw(8),
    backgroundColor: '#F5F7FA',
    paddingHorizontal: sw(16),
    paddingVertical: sh(10),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e8eaed',
  },
  secureText: {
    flex: 1,
    fontSize: ms(12),
    color: '#5f6368',
    fontWeight: '500',
    lineHeight: ms(17),
  },
  webview: { flex: 1 },
  loading: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.background,
  },
  loadingText: {
    marginTop: sh(12),
    fontSize: ms(14),
    color: '#5f6368',
  },
});
