import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/theme';
import { ms, sh, sw } from '@/utils/responsive';

export const companyRegistrationFormStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollContent: {
    padding: sw(20),
    paddingBottom: sh(48),
  },
  progressBar: {
    flexDirection: 'row',
    marginBottom: sh(24),
    gap: sw(8),
  },
  progressStep: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.borderLight,
  },
  progressStepActive: {
    backgroundColor: Colors.primary,
  },
  progressStepDone: {
    backgroundColor: Colors.primary,
    opacity: 0.6,
  },
  section: {
    marginBottom: sh(28),
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: sh(12),
  },
  sectionTitle: {
    fontSize: ms(18),
    fontWeight: '700',
    color: Colors.primary,
    marginBottom: sh(16),
  },
  sectionTitleCompact: {
    fontSize: ms(18),
    fontWeight: '700',
    color: Colors.primary,
    marginBottom: 0,
  },
  addDirectorBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sw(6),
    paddingVertical: sh(8),
    paddingHorizontal: sw(12),
  },
  addDirectorBtnText: {
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.primary,
  },
  directorCard: {
    backgroundColor: Colors.white,
    borderRadius: sw(20),
    padding: sw(18),
    marginBottom: sh(20),
    borderWidth: 0,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  directorCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: sh(16),
  },
  directorCardTitle: {
    fontSize: ms(16),
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  removeDirectorBtn: {
    padding: sw(4),
  },
  uploadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(8),
    paddingVertical: sh(12),
    paddingHorizontal: sw(16),
    borderRadius: sw(16),
    borderWidth: 1.5,
    borderColor: Colors.primary,
    backgroundColor: Colors.surface,
    marginBottom: sh(14),
  },
  uploadBtnError: {
    borderColor: '#ef4444',
    backgroundColor: '#fff5f5',
  },
  uploadBtnSuccess: {
    backgroundColor: '#22c55e',
    borderColor: '#22c55e',
  },
  uploadBtnText: {
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.primary,
  },
  uploadBtnTextSuccess: {
    color: '#fff',
  },
  // Upload modal
  uploadModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: sw(24),
  },
  uploadModalContent: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: Colors.white,
    borderRadius: sw(24),
    padding: sw(24),
  },
  uploadModalHeader: {
    marginBottom: sh(24),
  },
  uploadModalTitle: {
    fontSize: ms(20),
    fontWeight: '700',
    color: Colors.textPrimary,
    marginBottom: sh(4),
  },
  uploadModalSubtitle: {
    fontSize: ms(14),
    color: Colors.textMuted,
  },
  uploadModalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: sh(14),
    paddingHorizontal: sw(12),
    borderRadius: sw(12),
    backgroundColor: Colors.surface,
    marginBottom: sh(10),
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  uploadModalIconWrap: {
    width: sw(48),
    height: sw(48),
    borderRadius: sw(24),
    backgroundColor: Colors.surfaceAccent,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: sw(14),
  },
  uploadModalOptionText: {
    flex: 1,
  },
  uploadModalOptionTitle: {
    fontSize: ms(16),
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  uploadModalOptionDesc: {
    fontSize: ms(12),
    color: Colors.textMuted,
    marginTop: sh(2),
  },
  uploadModalCancelBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(8),
    marginTop: sh(16),
    paddingVertical: sh(12),
  },
  uploadModalCancelText: {
    fontSize: ms(15),
    fontWeight: '600',
    color: Colors.textMuted,
  },
  submitModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: sw(24),
  },
  submitModalCard: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: Colors.white,
    borderRadius: sw(24),
    paddingVertical: sh(24),
    paddingHorizontal: sw(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitModalTitle: {
    marginTop: sh(12),
    fontSize: ms(18),
    fontWeight: '700',
    color: Colors.textPrimary,
    textAlign: 'center',
  },
  submitModalSubtitle: {
    marginTop: sh(8),
    fontSize: ms(13),
    color: Colors.textMuted,
    textAlign: 'center',
    lineHeight: ms(18),
  },
  sectionSubtitle: {
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.textPrimary,
    marginBottom: sh(8),
  },
  input: {
    backgroundColor: Colors.white,
    borderRadius: sw(16),
    paddingHorizontal: sw(14),
    paddingVertical: sh(13),
    fontSize: ms(15),
    color: Colors.textPrimary,
    marginBottom: sh(14),
    borderWidth: 1,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  inputNoOutline: {
    borderWidth: 0,
    borderColor: 'transparent',
  },
  inputMultiline: {
    minHeight: sh(80),
    textAlignVertical: 'top',
  },
  inputError: {
    borderWidth: 1.5,
    borderColor: '#ef4444',
    backgroundColor: '#fff5f5',
  },
  label: {
    fontSize: ms(13),
    fontWeight: '600',
    color: Colors.textPrimary,
    marginBottom: sh(6),
  },
  row: {
    flexDirection: 'row',
    gap: sw(12),
  },
  rowItem: {
    flex: 1,
  },
  disclaimerBlock: {
    marginTop: sh(4),
    marginBottom: sh(20),
    paddingHorizontal: sw(4),
    paddingVertical: 0,
  },
  disclaimerText: {
    fontSize: ms(14),
    color: Colors.textSecondary,
    lineHeight: ms(22),
    marginBottom: sh(14),
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sw(12),
    borderRadius: sw(14),
    padding: sw(10),
  },
  checkboxRowError: {
    borderWidth: 1,
    borderColor: '#ef4444',
    backgroundColor: '#fff5f5',
  },
  checkboxLabel: {
    flex: 1,
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.textPrimary,
    lineHeight: ms(20),
  },
  ctaButton: {
    backgroundColor: Colors.primary,
    paddingVertical: sh(16),
    borderRadius: sw(18),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  ctaButtonDisabled: {
    opacity: 0.5,
  },
  ctaButtonText: {
    fontSize: ms(16),
    fontWeight: '700',
    color: Colors.textOnPrimary,
  },
  validationHint: {
    fontSize: ms(13),
    fontWeight: '600',
    color: '#dc2626',
    marginBottom: sh(14),
  },
  nextButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(8),
    backgroundColor: Colors.primary,
    paddingVertical: sh(14),
    paddingHorizontal: sw(20),
    borderRadius: sw(14),
    marginTop: sh(20),
  },
  nextButtonText: {
    fontSize: ms(16),
    fontWeight: '700',
    color: Colors.textOnPrimary,
  },
  caseCard: {
    backgroundColor: Colors.surfaceLight,
    borderRadius: sw(16),
    padding: sw(18),
    marginBottom: sh(24),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  caseCardTitle: {
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.textMuted,
    marginBottom: sh(6),
  },
  caseIdText: {
    fontSize: ms(20),
    fontWeight: '800',
    color: Colors.primary,
    marginBottom: sh(12),
    letterSpacing: 1,
  },
  caseCardSubtitle: {
    fontSize: ms(12),
    fontWeight: '600',
    color: Colors.textSecondary,
    marginBottom: sh(8),
  },
  caseDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: sh(6),
  },
  caseDetailLabel: {
    fontSize: ms(13),
    color: Colors.textMuted,
  },
  caseDetailValue: {
    fontSize: ms(13),
    fontWeight: '600',
    color: Colors.textPrimary,
    flex: 1,
    marginLeft: sw(8),
    textAlign: 'right',
  },
  caseCardHint: {
    fontSize: ms(12),
    color: Colors.textSecondary,
    marginTop: sh(12),
    fontStyle: 'italic',
  },
});
