import { Platform, StyleSheet } from 'react-native';
import { Colors } from '@/constants/theme';
import { ms, sh, sw } from '@/utils/responsive';

export const companyRegistrationFormStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  scrollContent: {
    padding: sw(20),
    paddingBottom: sh(48),
    flexGrow: 1,
    minHeight: '100%',
  },
  progressBar: {
    flexDirection: 'row',
    marginBottom: sh(24),
    gap: sw(8),
  },
  progressStep: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.borderLight,
  },
  progressStepActive: {
    backgroundColor: Colors.primary,
  },
  progressStepDone: {
    backgroundColor: Colors.primary,
    opacity: 0.6,
  },
  section: {
    marginBottom: sh(28),
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: sh(12),
  },
  sectionTitle: {
    fontSize: ms(22),
    fontWeight: '700',
    color: '#202124',
    marginBottom: sh(4),
    letterSpacing: 0,
  },
  sectionTitleCompact: {
    fontSize: ms(22),
    fontWeight: '700',
    color: '#202124',
    marginBottom: 0,
  },
  sectionLead: {
    fontSize: ms(14),
    fontWeight: '400',
    color: Colors.textSecondary,
    lineHeight: ms(20),
    marginBottom: sh(20),
  },
  addDirectorBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sw(6),
    paddingVertical: sh(8),
    paddingHorizontal: sw(12),
  },
  addDirectorBtnText: {
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.primary,
  },
  directorCard: {
    backgroundColor: Colors.background,
    borderRadius: sw(12),
    padding: sw(16),
    marginBottom: sh(16),
    borderWidth: 1,
    borderColor: '#e8eaed',
  },
  directorCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: sh(16),
  },
  directorCardTitle: {
    fontSize: ms(16),
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  removeDirectorBtn: {
    padding: sw(4),
  },
  uploadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(8),
    paddingVertical: sh(12),
    paddingHorizontal: sw(16),
    borderRadius: sw(16),
    borderWidth: 1.5,
    borderColor: Colors.primary,
    backgroundColor: Colors.surface,
    marginBottom: sh(14),
  },
  uploadBtnError: {
    borderColor: '#ef4444',
    backgroundColor: '#fff5f5',
  },
  uploadBtnSuccess: {
    backgroundColor: '#22c55e',
    borderColor: '#22c55e',
  },
  uploadBtnText: {
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.primary,
  },
  uploadBtnTextSuccess: {
    color: '#fff',
  },
  // Upload modal
  uploadModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: sw(24),
  },
  uploadModalContent: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: Colors.white,
    borderRadius: sw(24),
    padding: sw(24),
  },
  uploadModalHeader: {
    marginBottom: sh(24),
  },
  uploadModalTitle: {
    fontSize: ms(20),
    fontWeight: '700',
    color: Colors.textPrimary,
    marginBottom: sh(4),
  },
  uploadModalSubtitle: {
    fontSize: ms(14),
    color: Colors.textMuted,
  },
  uploadModalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: sh(14),
    paddingHorizontal: sw(12),
    borderRadius: sw(12),
    backgroundColor: Colors.surface,
    marginBottom: sh(10),
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  uploadModalIconWrap: {
    width: sw(48),
    height: sw(48),
    borderRadius: sw(24),
    backgroundColor: Colors.surfaceAccent,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: sw(14),
  },
  uploadModalOptionText: {
    flex: 1,
  },
  uploadModalOptionTitle: {
    fontSize: ms(16),
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  uploadModalOptionDesc: {
    fontSize: ms(12),
    color: Colors.textMuted,
    marginTop: sh(2),
  },
  uploadModalCancelBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(8),
    marginTop: sh(16),
    paddingVertical: sh(12),
  },
  uploadModalCancelText: {
    fontSize: ms(15),
    fontWeight: '600',
    color: Colors.textMuted,
  },
  submitModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: sw(24),
  },
  submitModalCard: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: Colors.white,
    borderRadius: sw(24),
    paddingVertical: sh(24),
    paddingHorizontal: sw(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitModalTitle: {
    marginTop: sh(12),
    fontSize: ms(18),
    fontWeight: '700',
    color: Colors.textPrimary,
    textAlign: 'center',
  },
  submitModalSubtitle: {
    marginTop: sh(8),
    fontSize: ms(13),
    color: Colors.textMuted,
    textAlign: 'center',
    lineHeight: ms(18),
  },
  sectionSubtitle: {
    fontSize: ms(13),
    fontWeight: '600',
    color: '#5f6368',
    marginBottom: sh(12),
    marginTop: sh(4),
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  input: {
    backgroundColor: Colors.white,
    borderRadius: sw(16),
    paddingHorizontal: sw(14),
    paddingVertical: sh(13),
    fontSize: ms(15),
    color: Colors.textPrimary,
    marginBottom: sh(14),
    borderWidth: 1,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  inputNoOutline: {
    borderWidth: 0,
    borderColor: 'transparent',
  },
  inputMultiline: {
    minHeight: sh(80),
    textAlignVertical: 'top',
  },
  inputError: {
    borderWidth: 1.5,
    borderColor: '#ef4444',
    backgroundColor: '#fff5f5',
  },
  fieldError: {
    fontSize: ms(12),
    color: '#ef4444',
    marginTop: sh(-8),
    marginBottom: sh(10),
  },
  label: {
    fontSize: ms(13),
    fontWeight: '600',
    color: Colors.textPrimary,
    marginBottom: sh(6),
  },
  row: {
    flexDirection: 'row',
    gap: sw(12),
  },
  rowItem: {
    flex: 1,
  },
  disclaimerBlock: {
    marginTop: sh(4),
    marginBottom: sh(20),
    paddingHorizontal: sw(4),
    paddingVertical: 0,
  },
  disclaimerText: {
    fontSize: ms(14),
    color: Colors.textSecondary,
    lineHeight: ms(22),
    marginBottom: sh(14),
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: sw(12),
    borderRadius: sw(14),
    padding: sw(10),
  },
  checkboxRowError: {
    borderWidth: 1,
    borderColor: '#ef4444',
    backgroundColor: '#fff5f5',
  },
  checkboxLabel: {
    flex: 1,
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.textPrimary,
    lineHeight: ms(20),
  },
  ctaButton: {
    backgroundColor: Colors.primary,
    minHeight: sh(52),
    borderRadius: sw(8),
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  ctaButtonDisabled: {
    opacity: 0.5,
  },
  ctaButtonText: {
    fontSize: ms(16),
    fontWeight: '600',
    color: Colors.textOnPrimary,
    letterSpacing: 0.25,
  },
  validationHint: {
    fontSize: ms(13),
    fontWeight: '500',
    color: '#d93025',
    marginBottom: sh(16),
    paddingVertical: sh(12),
    paddingHorizontal: sw(14),
    backgroundColor: '#fce8e6',
    borderRadius: sw(8),
    overflow: 'hidden',
  },
  nextButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: sw(8),
    backgroundColor: Colors.primary,
    minHeight: sh(52),
    paddingHorizontal: sw(20),
    borderRadius: sw(8),
    marginTop: sh(8),
    width: '100%',
  },
  nextButtonText: {
    fontSize: ms(16),
    fontWeight: '600',
    color: Colors.textOnPrimary,
    letterSpacing: 0.25,
  },
  caseCard: {
    backgroundColor: Colors.background,
    borderRadius: sw(8),
    paddingVertical: sh(10),
    paddingHorizontal: sw(14),
    marginBottom: sh(16),
    borderWidth: 1,
    borderColor: '#e8eaed',
  },
  caseCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: sw(10),
  },
  caseCardTitle: {
    fontSize: ms(11),
    fontWeight: '500',
    color: '#5f6368',
    marginBottom: sh(2),
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  caseIdText: {
    fontSize: ms(17),
    fontWeight: '600',
    color: '#202124',
    letterSpacing: 0.15,
  },
  caseStatusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: sw(4),
    paddingHorizontal: sw(10),
    paddingVertical: sh(4),
    borderRadius: sw(16),
  },
  caseStatusChipText: {
    fontSize: ms(11),
    fontWeight: '600',
  },
  caseCardHint: {
    fontSize: ms(11),
    color: '#5f6368',
    marginTop: sh(8),
    lineHeight: ms(15),
  },
  recheckOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  recheckSheet: {
    backgroundColor: Colors.background,
    borderTopLeftRadius: sw(16),
    borderTopRightRadius: sw(16),
    maxHeight: '88%',
    paddingBottom: Platform.OS === 'ios' ? sh(28) : sh(16),
  },
  recheckHandle: {
    width: sw(36),
    height: sh(4),
    borderRadius: 2,
    backgroundColor: '#dadce0',
    alignSelf: 'center',
    marginTop: sh(10),
    marginBottom: sh(8),
  },
  recheckHeader: {
    paddingHorizontal: sw(20),
    paddingBottom: sh(12),
  },
  recheckTitle: {
    fontSize: ms(20),
    fontWeight: '700',
    color: '#202124',
    marginBottom: sh(4),
  },
  recheckSubtitle: {
    fontSize: ms(14),
    fontWeight: '400',
    color: Colors.textSecondary,
    lineHeight: ms(20),
  },
  recheckScrollHint: {
    fontSize: ms(12),
    fontWeight: '500',
    color: '#80868b',
    marginTop: sh(8),
  },
  recheckScroll: {
    marginHorizontal: sw(4),
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#e8eaed',
  },
  recheckScrollContent: {
    paddingHorizontal: sw(16),
    paddingVertical: sh(4),
    paddingBottom: sh(12),
  },
  recheckRow: {
    flexDirection: 'row',
    paddingVertical: sh(10),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e8eaed',
    gap: sw(12),
  },
  recheckRowLabel: {
    width: sw(110),
    fontSize: ms(13),
    fontWeight: '500',
    color: '#5f6368',
  },
  recheckRowValue: {
    flex: 1,
    fontSize: ms(14),
    fontWeight: '400',
    color: '#202124',
    lineHeight: ms(20),
  },
  recheckActions: {
    paddingHorizontal: sw(20),
    paddingTop: sh(16),
    gap: sh(10),
  },
  recheckBackBtn: {
    alignItems: 'center',
    paddingVertical: sh(12),
  },
  recheckBackText: {
    fontSize: ms(14),
    fontWeight: '600',
    color: Colors.primary,
  },
  caseCardSubtitle: {
    fontSize: ms(12),
    fontWeight: '600',
    color: Colors.textSecondary,
    marginBottom: sh(8),
  },
  caseDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: sh(6),
  },
  caseDetailLabel: {
    fontSize: ms(13),
    color: Colors.textMuted,
  },
  caseDetailValue: {
    fontSize: ms(13),
    fontWeight: '600',
    color: Colors.textPrimary,
    flex: 1,
    marginLeft: sw(8),
    textAlign: 'right',
  },
});
